### ISSUE TITLE
HASS - Create Devices for Scenes

### ISSUE THREAD

**Issue by rmkraus** [automicus/PyISY#131]
The family and I just settled back down in a permanent home after being in transition for the past two years. Obviously, getting HASS and the ISY back up was a priority. Thanks for all the hard work you have all done on this library and the HASS integration. I can't tell you how humbling it is to see this project evolve way past my initial contributions. Both HASS and the ISY integrations have come so far in the past two years.

With that said, I had a question that I wanted to ask in this venue first: Why are no devices created to go along with the switches for scenes in HASS? I'd like to put my scenes into areas, but I can't do that atm.

**Comment by shbatm** [comment]
@rmkraus I'm glad I've been able to contribute and share, but it would not have been close to what it is without your original framework. I'm glad you're finally getting to settle back into a permanent spot! Going on 3 months of a move myself and I'm already sick of it.

As for the devices, when I added the support, my interpretation per the [guidance](https://developers.home-assistant.io/docs/device_registry_index/) was they were only for physical devices. That was also before Areas were really useful.

I think it'd be best to follow the lead from the Insteon PLM and Z-Wave integrations, when I get a chance I'll take a look at how they're handling native device scenes.

**Comment by shbatm** [comment]
@bdraco Thoughts on this?

**Comment by bdraco** [comment]
I read the docs the same way.

I think its best to open an architecture (https://github.com/home-assistant/architecture/issues/new) for clarification if the docs be changed to `"physical" or "virtual" device`

**Comment by shbatm** [comment]
@teharris1 - want to get your thoughts on this and doing some research as well before I take it to `architecture`. How does the Insteon integration handle scenes vs. how should they be handled.

To me the Architecture issue would be: 

** Device Creation / Area Assignment for Scenes in External Protocols ** 

This applies to Z-Wave Scenes (Z-Wave, OpenZWave, Zwave2mqtt), Zigbee Groups (ZHA, zigbee2mqtt), Insteon Scenes (Insteon PLM, ISY994), and maybe even some of the RF protocols as well like RFLink

Questions include:
1) Can/should Home Assistant `devices` be created for an external protocol's scenes/groups/virtual devices, rather than for just individual physical devices?
2) If not is there another way these should be presented so they can be added to Areas and better controlled with the newer Automation engine?
3) Can/should entities in those scenes/groups also be included in the device in Home Assistant? Said another way: if I have 5 devices in an Insteon/ISY Scene, should the device in Home Assistant list the scene entity, as well as all the responders, or just the scene entity? (Can entities be listed under multiple devices?)

**Comment by OverloadUT** [comment]
The `hue.hue_activate_scene` service in Hue is another one to add to the list of components that use similar functionality

I've long wished for Home Assistant to get first class support for these sort of ecosystem-specific scenes. It's a tough one because each ecosystem is likely to have very different needs and features (turning a scene off is a good example that appears to be pretty unique to Insteon), so I am in full support of opening the architecture issue. I'd be happy to chime in there with my thoughts as well.

**Comment by teharris1** [comment]
I have been asked a similar request on the Insteon side. Unfortunately, I don't agree with creating scenes as devices for a few reasons. Most importantly, an Insteon scene is a trigger, not a `device` therefore it does not have state, The devices that the scene triggers have state. I get the idea of having one "entity" that can turn a scene on/off and could give you the state of the scene in some way but that has a lot of challenges to it. For example, the definition of a scene would need to be exposed to HA in some way that it could know the state of the scene which really means knowing the state of each device in the scene. This could, in some way, be done manually today with a combination of a helper switch and a few automations. But that requires redefining the scene in the automations and it requires the user to have a technical ability to think through the scenes. 

What I think I am in favor of is having a device or entity group that has reference to other devices and or other entities. This would allow you to use existing HA functionality to track the state of a group. The 3-way switch concept here is the most obvious but it could also be good for other scenarios. It could give you the state of a scene by showing the state of the underlying entities the scene controls. The question is if it would be read-only or be a switch to trigger the scene on/off. 

To @OverloadUT point, turning a scene off is not a native function to many platforms. And in fact, even in Insteon it is a wierd implementation (i.e it assumes the off state of a scene is all the devices moving to the off state, but what if one of the states of a scene is to turn a device off, shouldn't the off state of the scene be to turn the device on or back to the state the device was in before the scene was triggered? but I digress.).  

The reason I say "I think" I am in favor is that the implementation of this has some difficult questions. 
1) Is this something the integration developer does or is this a user function
2) If this is a user function, is it cross integration or only within the same integration
3) is it read-only or interactive
4) If it is interactive, what platform does it support (ie. could you group a thermostat temp and a light switch) 

The most compelling reason to do this in my mind is the 3-way switch. I am curious about what other use cases this would solve.

> I've long wished for Home Assistant to get first class support for these sort of ecosystem-specific scenes.

I think this is a good point by the way but I just don't think they are devices. From my perspective, they are a trigger as I said. Perhaps the best answer is to extend the current HA scene capability to include platform specific scene features. This way, inside HA you could create an HA scene that can be cross platform actions or a platform specific scene that would be a first class object in HA.

**Comment by shbatm** [comment]
I'm going to close this for now, as it doesn't look like there's much support to make scenes devices on the Home Assistant side; however, the original request was to do so that way they could be added to Areas in Home Assistant. You can now add entities themselves to areas to accomplish the same thing.
