### ISSUE TITLE
Z-Wave Devices using 0-100% instead of 0-255 for the Brightness

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#141]
This seems like an long-running but un-tracked bug where certain Z-Wave devices use UOM=51 and 0-100% instead of the 0-255 used by most devices.

Two options -- update `Nodes` here to use catch `uom=51` devices and translate to 0-255, or update Home Assistant to do the same.

I will double check to make sure this was not a regression missed in V2, but I think it's just been worked around since there were limited users.

References:

- https://community.home-assistant.io/t/brightness-0-100-not-255/77107/20
- https://github.com/shbatm/hacs-isy994/issues/76

**Comment by Mandaur1** [comment]
The uom designation for % on the isy in node properties is 51. It was lost between us communicating. I also noticed that the formatted field when looking at the xml node properties shows % vs Insteon devices showing off.

**Comment by kj4qyf** [comment]
It is not my only issue. When changing  the circle (%) in HA on a dimming light, nothing happens to the light and nothing shows up in ISY

**Comment by shbatm** [comment]
> It is not my only issue. When changing the circle (%) in HA on a dimming light, nothing happens to the light and nothing shows up in ISY

Please provide the XML from http://your-isy-ip:port/rest/nodes/ZW_ADDRESS_OF_NODE when you get a chance. This will provide the device details for some diagnostics.

Does it do anything when you change the dimming in the 0-40% range? Also, can you please try browsing to the following address using your browser and see if the light dims to 50%? http://your-isy-ip:port/rest/nodes/ZW_ADDRESS_OF_NODE/cmd/DON/50

**Comment by kj4qyf** [comment]
[ZW139_01.pdf](https://github.com/automicus/PyISY/files/5475988/ZW139_01.pdf)
[50.pdf](https://github.com/automicus/PyISY/files/5475989/50.pdf)
[ZW048_01.pdf](https://github.com/automicus/PyISY/files/5475991/ZW048_01.pdf)
ZW048 is the Office Night Light. And I also did the same for another light ZW139
It seems indeed that the ISY and the light react to a HA change of % up to 40% and not higher.
Let me know if you need anything else. Thanks again for your kind and prompt attention

**Comment by shbatm** [comment]
OK, then it's definitely due to this issue: 39% is 100/255--since the Z-Wave light is expecting a 0-100 range instead of 0-255 like all other ISY devices, it doesn't know what to do if you send higher than 100.

Can you please resend the XML file using `/ZW048_1` instead of `/ZW048_01` that should get rid of the 404 error.

**Comment by kj4qyf** [comment]
[ZW048_1.pdf](https://github.com/automicus/PyISY/files/5476513/ZW048_1.pdf)

**Comment by kj4qyf** [comment]
OK, then it's definitely due to this issue: 39% is 100/255--since the Z-Wave light is expecting a 0-100 range instead of 0-255 like all other ISY devices, it doesn't know what to do if you send higher than 100.


That makes sense. Thanks

**Comment by kj4qyf** [comment]
UDi has asked that you kindly coordinate the resolution of the 0-100   
vs 0-255 issue with them, as they want to make sure that it not creates 
a conflict elsewhere.


Many thanks

------ Original Message ------

**Comment by kj4qyf** [comment]
----- Please reply above this line ------- Status: Open-- For full conversation/history, please click https://www.universal-devices.com/my-tickets/?support_page=open_ticket&ticket_id=10402&auth_code=DNQL9NzjGz
Dear Abraham Seno BRIL,
Thank you for contacting us. We'll do our best to get back to you as soon as possible and, usually, within 2 hours but no later than 48 hours. In the meantime, please 1. Checkout our Wiki wherein you will find a wealth of information on almost any topic including complete guides and cookbooks, examples, videos, and even tutorials2. Visit our forum wherein, not only you can enjoy searching/reading about all ISY topics, but also you'll get to meet 1000s of our community members who can answer your questions3. If you have not yet registered for our site, please do so as it will help you manage all your interactions with us including the status of this ticket! 
Our office hours are:Monday through Friday 8:00 AM to 5:00 PM Pacific Time.
With kind regards,Universal Devices Support Team

**Comment by kj4qyf** [comment]
----- Please reply above this line ------- Assigned to: Brad McAdams, michel@universal-devices.com | Support/Low | Status: Open -- Product Info:  -- Ticket link: https://www.universal-devices.com/my-tickets/?support_page=open_ticket&ticket_id=10402&auth_code=DNQL9NzjGz
Abraham Seno BRIL wrote:

UDi has asked that you kindly coordinate the resolution of the 0-100   vs 0-255 issue with them, as they want to make sure that it not creates a conflict elsewhere.Many thanks

------ Original Message ------

**Comment by kj4qyf** [comment]
----- Please reply above this line ------- Assigned to: Brad McAdams, michel@universal-devices.com | Support/Low | Status: Awaiting customer reply -- Product Info:  -- Ticket link: https://www.universal-devices.com/my-tickets/?support_page=open_ticket&ticket_id=10402&auth_code=DNQL9NzjGz
michel@universal-devices.com wrote:













Thank you Seno.
 
With kind regards,
 
******************************
  Michel Kohanim
  CEO
 
  (p) 818.631.0333
  
http://www.universal-devices.com 
******************************
 

From: UD Support <support@universal-devices.com> 
Sent: Tuesday, November 3, 2020 7:15 AM
To: Bradford C. McAdams <brad@universal-devices.com>
Subject: [Ticket #10402] Abraham Seno BRIL | Re[2]: [automicus/PyISY] Z-Wave Devices using 0-100% instead of 0-255 for the Brightness (#141)

 
----- Please reply above this line -----
-- Assigned to: Brad McAdams, michel@universal-devices.com | Support/Low | Status: Open 
-- Product Info: 
-- Ticket link: 
https://www.universal-devices.com/my-tickets/?support_page=open_ticket&ticket_id=10402&auth_code=DNQL9NzjGz
Abraham Seno BRIL wrote:

UDi has asked that you kindly coordinate the resolution of the 0-100   vs 0-255 issue with them, as they want to make sure that it not
 creates a conflict elsewhere.


 


 


Many thanks


 


------ Original Message ------

**Comment by shbatm** [comment]
Looking into this more, IMO the best place to fix it is going to be in the Home Assistant code, since the scope of when you need to check for this and how you keep track of the % vs the 8-bit value can be narrowed down better in Home Assistant's integration vs. here. I have initiated the PR over on the Home Assistant side to resolve.

**Comment by kj4qyf** [comment]
Many thanks.  I look forward hearing from HA on the solution. I also understand that there may be a ISY specific issue, whereby Insteon devices work with 0-255 while Zwave with 0-100  (or the reverse).
Many thanks to all and hopefully this can be resolved soon.

**Comment by shbatm** [comment]
Closed via home-assistant/core#42915.

**Comment by kj4qyf** [comment]
I don't understand why this closed while it has not been resolved.
I am copying UDI (ISY994i) as this concerns them as well

Thanks

------ Original Message ------

**Comment by kj4qyf** [comment]
----- Please reply above this line ------- Status: Open-- For full conversation/history, please click https://www.universal-devices.com/my-tickets/?support_page=open_ticket&ticket_id=10441&auth_code=CtC4PEq4SA
Dear Harry,
Thank you for contacting us. We'll do our best to get back to you as soon as possible and, usually, within 2 hours but no later than 48 hours. In the meantime, please 1. Checkout our Wiki wherein you will find a wealth of information on almost any topic including complete guides and cookbooks, examples, videos, and even tutorials2. Visit our forum wherein, not only you can enjoy searching/reading about all ISY topics, but also you'll get to meet 1000s of our community members who can answer your questions3. If you have not yet registered for our site, please do so as it will help you manage all your interactions with us including the status of this ticket! 
Our office hours are:Monday through Friday 8:00 AM to 5:00 PM Pacific Time.
With kind regards,Universal Devices Support Team

**Comment by kj4qyf** [comment]
----- Please reply above this line ------- Assigned to: Brad McAdams, michel@universal-devices.com | Support/Low | Status: Open -- Product Info:  -- Ticket link: https://www.universal-devices.com/my-tickets/?support_page=open_ticket&ticket_id=10441&auth_code=CtC4PEq4SA
Harry wrote:

I don't understand why this closed while it has not been resolved.I am copying UDI (ISY994i) as this concerns them as wellThanks

------ Original Message ------

**Comment by rccoleman** [comment]
The corresponding PR to the Home Assistant Core mentioned above has been merged. Nothing to be concerned about.

**Comment by kj4qyf** [comment]
----- Please reply above this line ------- Assigned to: Brad McAdams, michel@universal-devices.com | Support/Low | Status: Awaiting customer reply -- Product Info:  -- Ticket link: https://www.universal-devices.com/my-tickets/?support_page=open_ticket&ticket_id=10441&auth_code=CtC4PEq4SA
michel@universal-devices.com wrote:













Hi Harry,
 
This is normal. In 5.x, UOM and ranges are defined by each protocol. For INSTEON, it’s 0-255. For Z-Wave, it’s 0-100.
 
With kind regards,
 
******************************
  Michel Kohanim
  CEO
 
  (p) 818.631.0333
  
http://www.universal-devices.com 
******************************
 

From: UD Support <support@universal-devices.com> 
Sent: Friday, November 6, 2020 12:55 PM
To: Bradford C. McAdams <brad@universal-devices.com>
Subject: [Ticket #10441] Harry | Re[2]: [automicus/PyISY] Z-Wave Devices using 0-100% instead of 0-255 for the Brightness (#141)

 
----- Please reply above this line -----
-- Assigned to: Brad McAdams, michel@universal-devices.com | Support/Low | Status: Open 
-- Product Info: 
-- Ticket link: 
https://www.universal-devices.com/my-tickets/?support_page=open_ticket&ticket_id=10441&auth_code=CtC4PEq4SA
Harry wrote:

I don't understand why this closed while it has not been resolved.


I am copying UDI (ISY994i) as this concerns them as well


 


Thanks


 


------ Original Message ------

**Comment by kj4qyf** [comment]
Thanks !!!!!!!!!!!!!!!!!!!!!!!!!!

------ Original Message ------

**Comment by shbatm** [comment]
The fix will be available in the next release cycle of Home Assistant. As mentioned by UDI, this is a normal/expected behavior on their end and just requires special handling from the HA end. 

Nothing is being changed in PyISY since this primarily concerns device/type-specific behaviors which are handled in Home Assistant.

**Comment by kj4qyf** [comment]
Understood and thanks !!!!!!!

------ Original Message ------

**Comment by rccoleman** [comment]
Heading off the next question - the release calendar is here: https://developers.home-assistant.io/

**Comment by Mandaur1** [comment]
Thank for making the changes to the HA core on dimming zwave devices. So I tested the new code. I have one question. I believe most light devices are able to go full range 0-255 where 0 is off and 255 is fully on. I think that the scaling factor in the code is not able to reach zero.  When I attempt to take the slider in HA to 0% in ends up on 1% or 3 on a scale of 0-255. I’m not sure if this was intentional.

**Comment by MechEng70** [comment]
Also, the last brightness is on the 0-255 scale and not the 0-100. Can that be changed to the same scale?

![last brightness](https://user-images.githubusercontent.com/11697710/101063276-7d88ce80-3547-11eb-8fa8-e5746c64fa0e.png)

**Comment by shbatm** [comment]
@Mandaur1:

> Thank for making the changes to the HA core on dimming zwave devices. So I tested the new code. I have one question. I believe most light devices are able to go full range 0-255 where 0 is off and 255 is fully on. I think that the scaling factor in the code is not able to reach zero. When I attempt to take the slider in HA to 0% in ends up on 1% or 3 on a scale of 0-255. I’m not sure if this was intentional.

I believe this behavior is part of Home Assistant's front-end. I just tried with a few other integrations and if using the slider, you can only go to 1%, to turn it off, you have to use the toggle or click the icon.


@MechEng70

> Also, the last brightness is on the 0-255 scale and not the 0-100. Can that be changed to the same scale?

This is also part of Home Assistant. Home Assistant works in 0-255 scale for brightness (regardless of integration), the changes made under this issue just translates between the 0-100 of the ISY and 0-255 for Home Assistant. You can use a template to translate this to 0-100% if you really need it..
