### ISSUE TITLE
Where did the documentation go?

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#147]
There used to be documentation on how to use the library, where did it go?

**Comment by shbatm** [comment]
Good question. I did not update any docs (just the in-code documentation) for v2, but I also don't remember deleting them.

I think @rmkraus had them hosted on the automic.us website, but that was a dead link by the time I started using the module a few years ago.

I found the old Sphinx folder with the last set of documentation updates ~6 years ago here:
https://github.com/automicus/PyISY/tree/ff11c810d4ca874e3d0ea688d09707ef6997e1ed/docs

Can still be used as a guide for most things, but I'll work on updating something for V2 & V3.

**Comment by jimboca** [comment]
Thanks!  We are considering pulling it into Polyglot V3 for those nodeservers that need direct access to the ISY, so docs would help others.

**Comment by shbatm** [comment]
10-4; hoping to have time to polish up PyISY V3 in the next month; work & life has gotten in the way. I will get docs cleaned up too and re-posted.

Is Polyglot V3 going to be fully async? It's been a long time since I've been in the NodeServer code and I can't remember. Curious just because it may change which PyISY branch you'd have to target.

**Comment by jimboca** [comment]
Thanks! Understand about work and life, same here.
Polyglot is a sync, but the python interface to it is not. Maybe do that with v4, but it may not really be necessary.

**Comment by shbatm** [comment]
Initial demo is live on https://pyisy.readthedocs.io/

I will work on updating as I polish up the V3 code.

**Comment by jimboca** [comment]
Nice! Thank you.
