### ISSUE TITLE
Error possibly due to python 2.7 mindom

### ISSUE THREAD

**Issue by jimboca** [automicus/PyISY#5]
When I try using this with my Python 2.7 I get errors similar to below.  When I run with Python 3.2 I do not have any issues.  I suspect it's an issue with the minidom version in 2.7?

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../PyISY/PyISY/Events/events.py", line 200, in watch
    self._routemsg(data)
  File "../PyISY/PyISY/Events/events.py", line 72, in _routemsg
    self.parent.nodes._upmsg(xmldoc)
  File "../PyISY/PyISY/Nodes/__init__.py", line 140, in _upmsg
    self.getByID(nid).status.update(nval, force=True, silent=True)
  File "../PyISY/PyISY/Nodes/__init__.py", line 294, in getByID
    i = self.nids.index(nid)
ValueError: u'1A AC A8 1' is not in list
```
Let me know how I can help debug this.  I'd like this to run with 2.7 since that is the default version on RPI, and I have issues with other modules like web.py on 3.2 so I'd like to stay on 2.7 if possible?

Thanks,
Jim

**Comment by rmkraus** [comment]
Does this happen when PyISY is running and then you add a node to the ISY?

**Comment by jimboca** [comment]
I have not added any new nodes, and this exact error shows up every time I start my program for the same device.  But otherwise things seem to work.

And the log has this:
```
DEBUG:root:ISY Update Received:
<?xml version="1.0"?><Event seqnum="4" sid="uuid:223"><control>_0</control><action>120</action><node></node><eventInfo></eventInfo></Event>
DEBUG:root:ISY HEARTBEAT: 2015-08-08T15:31:48.439588
DEBUG:root:ISY Update Received:
<?xml version="1.0"?><Event seqnum="5" sid="uuid:223"><control>_19</control><action>6</action><node></node><eventInfo><se type="156" val="0" /></eventInfo></Event>
DEBUG:root:ISY Update Received:
<?xml version="1.0"?><Event seqnum="6" sid="uuid:223"><control>_19</control><action>6</action><node></node><eventInfo><se type="157" val="0" /></eventInfo></Event>
DEBUG:root:ISY Update Received:
<?xml version="1.0"?><Event seqnum="7" sid="uuid:223"><control>RR</control><action>31</action><node>1A AC A8 1</node><eventInfo></eventInfo></Event>
DEBUG:root:ISY Update Received:
<?xml version="1.0"?><Event seqnum="8" sid="uuid:223"><control>OL</control><action>255</action><node>1A AC A8 1</node><eventInfo></eventInfo></Event>
DEBUG:root:ISY Update Received:
<?xml version="1.0"?><Event seqnum="9" sid="uuid:223"><control>ST</control><action>0</action><node>1A AC A8 1</node><eventInfo></eventInfo></Event>
```

**Comment by rmkraus** [comment]
What is happening is the PyISY is receiving an update from the ISY over the event stream that is trying to update the ST (status) value of that node. The problem is that this node has, for some reason, not been added to the node tree inside of PyISY. I'm not sure why it works in 3.2 and not 2.7.

Could you do me two favors to help diagnose this error:
1) Copy the block for that node from http://ISY_ADDRESS/rest/nodes?members=false and attach it here.
2) After creating a PyISY instance, but before starting the event stream, print out isy.nodes.nids and attach it here.

Thanks. Also, just FYI, different installed modules will generally not conflict with each other in a single Python environment. However, if you would like to keep some separation between things (generally a good idea), you should check out Python Virtual Environments. As you get more into Python, you'll basically have to start using them, which is good, because they are super handy.

**Comment by jimboca** [comment]
It looks like I am getting no nodes when using Python 2.7, the list is empty.  So it makes sense that any devices that report a status cause an error once the event stream starts.  I thought things were working ok, but I have only been doing Variable setting so far, so I didn't notice.  I didn't attach what you requested, since it looks like I'll need to walk through to see why I'm not getting nodes, or I can send you anything you might think is helpful.  But, for now I have more of a need to have VarEvents added to ISY Variables, so I'll probably look at adding that first if you would be ok with it.

I'm slowly learning how python modules are installed, but getting web.py installed for 3.2 has me stumped for now.  I've seen the virtual environments and will look into those at some point...  Too many new things to figure out :-)

**Comment by rmkraus** [comment]
Well that is just all kinds of bad! I'm using the 1.0.6 version you just
submitted and I'm seeing all my nodes. Have you made any additional
changes? Nodes that contain <family>6</family> are ignored because they are
system nodes. That isn't showing up in all your nodes (in the XML from the
ISY) for some odd reason is it? As a tip, you can put in a a python
breakpoint by entering the following into a line:

import pdb; pdb.set_trace()

This will stop the code execution and enter an interactive shell. Type help
to see the options you have. I would recommend setting a breakpoint in
PyISY/Nodes/__init__.py line 157 and watching what happens in the loop the
second time around when PyISY should be importing the nodes.

PyISY variables do actually use VarEvents for their init, val, and lastEdit
properties. Is there something else you would want it used for?

Yeah, don't look into virtual environments yet, just know it is out there
for later. Python has evolved to have a MASSIVE ecosystem, which can be
overwhelming at first. One tool you will want to become familiar with,
however, is pip. Pip stands for Package Installer for Python. You can use
it to install any packages available at pypi.python.org (like PyISY). So to
install web.py, you can just type:

pip install web.py

However, since it sounds like you are using the default Python distribution
on the machine, you will need to run pip with admin privileges. To do this
in Linux, prepend the command sudo:

sudo pip install web.py

Hopefully that helps a bit.

Thanks,

Ryan Kraus

**Comment by jimboca** [comment]
No I have not changed anything else.  The insteon nodes don't have family in my xml, and z-wave nodes have <family>4</family>.

Thanks for the tips on the debugger, I will look into it.  Something I need to be more familiar with anyway.

I didn't think Variables used VarEvents because it didn't work the first time I tried it, but obviously I was doing it wrong, so that is great, and I'll try again.

I've become familiar with pip, and have used it for a bunch of modules, but web.py fails with a syntax error with Python 3.2, and some searching around didn't show anything obvious.  So I'll push onto that when I get time, or may be just install 3.4 since the instructions on the home-assistant site look pretty straight forward... Or maybe I'll wait till I get another RPi since that is probably in my future...

Thanks a lot, that does help.
- Jim

**Comment by jimboca** [comment]
I started with the debugger and quickly realized this was the error I had seen before with mindom on Python 2.7, I did not notice the log was saying:
ERROR:root:ISY Could not parse nodes, poorly formatted XML.
This works with minidom and python 3.2 :-(

**Comment by rmkraus** [comment]
Ok. If you would like, you could put in a break point before the xml
parsing, print the xml data out to a file, and then attach it. Then I'll
use this to try and figure out what is going on.

On Sunday, August 9, 2015, jimboca <notifications@github.com> wrote:

> I started with the debugger and quickly realized this was the error I had
> seen before with mindom on Python 2.7, I did not notice the log was saying:
> ERROR:root:ISY Could not parse nodes, poorly formatted XML.
> This works with minidom and python 3.2 :-(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/automicus/PyISY/issues/5#issuecomment-129213144>.
>


-- 
Thanks,

Ryan Kraus

**Comment by jimboca** [comment]
Ok, whats the best way?  I thought this would work:
```
(Pdb) fo = open("nodes.xml","w")
(Pdb) fo.write(xml)
*** UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 94678: ordinal not in range(128)
```
The first part looks like this:
```
(Pdb) p xml
u'<?xml version="1.0" encoding="UTF-8"?><nodes><root></root><folder flag="0"><address>13172</address><name>Kitchen</name><parent type="3">5
```

**Comment by rmkraus** [comment]
Ahh yes, that is Python saying that it cannot print the degrees symbol out
to an ASCII file because the degrees symbol is Unicode. In Python 2.7, do
this:

fo = open("nodes.xml", "w")
fo.write(xml.replace(u'\xb0', ''))
fo.close()

Thanks,

Ryan Kraus

**Comment by jimboca** [comment]
Ok, great.  I will email it to you.  I feel weird posting all my device address here...

**Comment by rmkraus** [comment]
Fair enough. I'll keep an eye out for it.

Thanks,

Ryan Kraus

**Comment by jimboca** [comment]
Ok, email sent.  Thanks for looking into it!

**Comment by rmkraus** [comment]
Do you have any ZWave temperature sensors?

**Comment by jimboca** [comment]
Yes, I have 2 different models of the Aeon multisensors, and some ZWave thermostats.

**Comment by rmkraus** [comment]
Try again with the newest version in master. I think I fixed your issue.

**Comment by jimboca** [comment]
Awesome, that did it!  thanks!

**Comment by rmkraus** [comment]
Great!
