### ISSUE TITLE
Set Variable Value Re-downloads ALL variables instead of using auto_update

### ISSUE THREAD

**Issue by shbatm** [automicus/PyISY#50]
When calling `setValue` [variable.py#L88](https://github.com/automicus/PyISY/blob/ff11c810d4ca874e3d0ea688d09707ef6997e1ed/PyISY/Variables/variable.py#L88) on a variable, there is:
 (a) `no return True` / `return False` like when calling [node.on()](https://github.com/automicus/PyISY/blob/ff11c810d4ca874e3d0ea688d09707ef6997e1ed/PyISY/Nodes/node.py#L237) or node.off() or program.run() etc. and 
 (b) Variables do not use the `if not self.parent.parent.auto_update:` conditional on the `update` calls that nodes use, nor do they make just a REST call to update their own value -- they call `/rest/vars/get/1` and `/rest/vars/get/2` and re-download all variable information (despite being connected to the event stream and getting the updates pushed from the ISY).

It looks like there were some changes made to clean up Nodes in the past and those changes were never added in to Variables. Capturing here as an issue--if I get a chance I will make these changes and fix.  

@rmkraus -- Any historical context on why `self.parent.parent.auto_update` is only used for Nodes?

**Comment by rmkraus** [comment]
I think I understand what you are saying and, unfortunately, I do not have much context here. It appears as if this code hasn't changed in the past 4 years so we are likely looking at most of the original code base here. 

Regarding the auto updating from the event stream, this was one of the last original features I built. Everything else was programmed and then I went back to add the event stream updates. I think I was hoping to get by without it. It is likely that I simply forgot to make this change to the variables code after adding the event stream feed.

So this issue is more of a performance issue rather than an actual functionality issue?

For reference, the commit that added the event stream: https://github.com/automicus/PyISY/commit/2f053b738dd8f961fd712ab440bf360dcf1b05f8
Unfortunately, that commit also includes a lot of ugly git practices that make me dislike former me. lol

**Comment by shbatm** [comment]
Thanks for the insight, that's kind of what I guessed.

Yes, this is mostly a performance issue I wanted to note and circle back later to fix if no one else gets a chance. I'm working on adding the ability to use Variables as sensors and switches in Home Assistant and noticed it. 

The only error I get from it is occasionally the ISY will only return one of the two variable calls, which throws an error in the `updateVariables` function in Connection.py. For some reason `updateVariables` is structured slightly differently from `getVariables` and doesn't handle this well.
